# Generated by Django 5.2 on 2025-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_chathistory_alter_document_vector_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
