# Generated by Django 5.2 on 2025-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_multifilechatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifilechatsession',
            name='vector_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
