# Generated by Django 5.2 on 2025-05-06 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_multifilechatsession_vector_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='chathistory',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rag.tenant'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multifilechatsession',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rag.tenant'),
        ),
        migrations.AddField(
            model_name='multifilechatsession',
            name='user_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='vector_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='chathistory',
            unique_together={('vector_id', 'user_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='multifilechatsession',
            unique_together={('vector_hash', 'user_identifier')},
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['vector_id', 'user_identifier'], name='rag_chathis_vector__b72ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='multifilechatsession',
            index=models.Index(fields=['vector_hash', 'user_identifier'], name='rag_multifi_vector__ad9994_idx'),
        ),
        migrations.AddIndex(
            model_name='multifilechatsession',
            index=models.Index(fields=['session_id'], name='rag_multifi_session_b17b8b_idx'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='rag.document'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together={('document', 'user_identifier')},
        ),
    ]
